[project]
name = "plotter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.3",
    "plotly>=5.24.1",
    "polars>=1.12.0",
    "pygame>=2.6.1",
    "rich>=13.9.4",
]
